services:

  go-cli-bundle:
    build:
      context: .
      dockerfile: Dockerfile-go.yml
    tty: true
    stdin_open: true
    environment:
      - TERM=xterm
    volumes:
      - ./data-go:/app # Replace with the actual path on your host machine
    working_dir: /app
    command: /bin/bash